[package]
name = "leptos-qr-scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.4.8", features = ["csr"] }
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3.64", features = ["HtmlVideoElement"] }
js-sys = "0.3.64"
console_error_panic_hook = "0.1"
console_log = { version = "1", features = ["color"] }
leptos_meta = { version = "0.4.6", features = ["csr"] }
